package com.example.demo;

import org.springframework.stereotype.Component;

@Component("excel")
public class ExcelReportGenerator implements ReportGenerator{

	@Override
	public void generateReport(String data) {
		System.out.println("Report Generated by Excel");
		System.out.println("The data is "+data);
	}

}
