package com.example.demo;

import org.springframework.stereotype.Component;

@Component("html")
public class HtmlReportGenerator implements ReportGenerator{

	@Override
	public void generateReport(String data) {
		System.out.println("Report Generated by html");
		System.out.println("The data is "+data);
	}

}
