package com.example.demo;

import org.springframework.stereotype.Component;

@Component("pdf")
public class PdfReportGenerator implements ReportGenerator{

	@Override
	public void generateReport(String data) {
		System.out.println("Report Generated by pdf");
		System.out.println("The data is "+data);
		
	}

}
